title:             宅男爱吐槽
email:             wangliming1991@sina.cn
description:       『我的第一次被冯兄给糟蹋了！』
author:             王兄
#baseurl:           "/startbootstrap-clean-blog-jekyll"
baseurl:           ""
url:               "http://fengmengzhao.github.io"

# Social Profiles
twitter_username:  #fengmengzhao
github_username:   FengMengZhao
facebook_username: #fengmengzhao

# 百度统计
analytics:
    baidu:
        siteid: a66e23d778dbfa813dcc8e5ad7b661ec

# Build settings
markdown:          kramdown
highlighter: rouge
paginate:          10 
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-slate
